// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaqnwuhtoeyqnkgmwkaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhcW53dWh0b2V5cW5rZ213a2FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzOTYzNDYsImV4cCI6MjA1MTk3MjM0Nn0.EpE2LaOnh59OMmuqRDDO0rrwV9PRMzXRS2MqaIrK6vA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);